# Generated by Django 4.1.3 on 2022-12-01 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('texto', models.TextField(null=True, verbose_name='Cuerpo de noticia')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado de activación')),
                ('imagen', models.ImageField(blank=True, default='noticia/default.png', null=True, upload_to='noticia', verbose_name='Imagen')),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticia.categoria')),
            ],
            options={
                'ordering': ('-publicado',),
            },
        ),
    ]
