# Generated by Django 4.1.3 on 2022-12-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_alter_noticia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, default='noticia/default.png', null=True, upload_to='noticia/', verbose_name='Imagen'),
        ),
    ]
