# Generated by Django 4.1.3 on 2022-12-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_alter_noticia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='nuevoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('pwd', models.CharField(max_length=150)),
                ('Edad', models.IntegerField()),
                ('Genero', models.CharField(max_length=150)),
                ('EstadoCivil', models.CharField(max_length=150)),
            ],
        ),
    ]
