# Generated by Django 4.1.3 on 2022-12-10 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0004_nuevousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
