# Generated by Django 4.1.3 on 2022-12-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0006_comentario_persona_delete_nuevousuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.IntegerField(default=1, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='username',
            field=models.CharField(max_length=35, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
