# Generated by Django 4.1.3 on 2022-12-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0009_rename_estado_noticia_estadonoticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadonoticia',
            name='nombre',
        ),
        migrations.AddField(
            model_name='estadonoticia',
            name='estado',
            field=models.CharField(default='Activo', max_length=35, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
