# Generated by Django 4.1.3 on 2022-12-11 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0011_remove_noticia_estadonoticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticia.estadonoticia', verbose_name='Categoría'),
        ),
    ]
