# Generated by Django 4.1.3 on 2022-12-11 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0012_noticia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=35, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='estado',
        ),
        migrations.DeleteModel(
            name='EstadoNoticia',
        ),
        migrations.AddField(
            model_name='noticia',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticia.status', verbose_name='Estado'),
        ),
    ]
